#pragma once
#ifndef CONFIG_H_
#define CONFIG_H_

#define DEFAULT_GAME_DATA_PATH "DEFAULT_GAME_DATA_PATH"
#define BASE_PLAYER_ENTITY_PATH "BASE_PLAYER_ENTITY_PATH"
#define DEFAULT_VOID_ROOM   "DEFAULT_VOID_ROOM"
#endif