#pragma once
#ifndef CONFIG_H_
#define CONFIG_H_

enum // Define log instances. Default is 0 and is omitted from this enum.
{
    RoomLog = 1
};


#define DEFAULT_GAME_DATA_PATH "DEFAULT_GAME_DATA_PATH"
#define BASE_PLAYER_ENTITY_PATH "BASE_PLAYER_ENTITY_PATH"
#define DEFAULT_VOID_ROOM   "DEFAULT_VOID_ROOM"
#define DEFAULT_DAEMON_PATH "DEFAULT_DAEMON_PATH"
#define DEFAULT_COMMANDS_PATH "DEFAULT_COMMANDS_PATH"
#define DEFAULT_COMMAND_PROC "DEFAULT_COMMAND_PROC"
#define DEFAULT_LIBS_PATH "DEFAULT_LIBS_PATH"
#define DEFAULT_LOGS_PATH "DEFAULT_LOGS_PATH"
#define DEFAULT_ROOM_LOG_PATH "DEFAULT_ROOM_LOG_PATH"
#endif